[project]
name = "dbt-stepik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.11.5",
    "dbt-postgres>=1.10.0",
    "sqlfluff>=4.0.4",
    "sqlfluff-templater-dbt>=4.0.4",
    "sqlfmt>=0.0.2",
]
